### ISSUE TITLE
project approval

### ISSUE THREAD

**Issue by CDSLabs** [sjsucmpe272-fall21/BlackSwanImpactPredictor#1]
I like your Idea#3 ... go for it.
alternatively, you should look for ideas in the following areas:

a) rising cost of securing software (cyber security/ data breach)
b) multi-cloud deployment of enterprise workload (fit for the purpose and cost-saving)
c) AI-powered data mapping and transformation in low code/no code tooling (talk to me if need more info)
d) AI in IT operations
e) AI in enterprise sales (talk to me if interested)

**Comment by puneettokhi** [comment]
@CDSLabs Hello Professor, thank you so much for approving our idea. I just have a quick question to ask you. So, I noticed that almost every team is building a web app for the project. However, our team was considering building an iOS app for our project, so would it be okay if we build an iOS app, or does it have to be a web app only?

Thank You
